version: '3.9'

services:

  backend:
    image: matheuscampelo/ada-flix-backend:latest
    container_name: ada-flix-backend
    ports:
      - "8080:8080"
    networks:
      - ada-flix-network

  frontend:
    image: matheuscampelo/ada-flix-frontend:latest
    container_name: ada-flix-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ada-flix-network

networks:
  ada-flix-network:
    driver: bridge
